Feature/153 task 02
felipedias-dev/helpper-origins-sprint-01 pull request #2
Opened 2021-10-30 23:47 UTC by felipedias-dev

2021-11-01 13:48 UTC, alanrocha-helpper requested changes

2021-11-01 13:48 UTC, alanrocha-helpper commented on src/task-2/item-a/index.ts
> +  for (let i = 0; i < persons.length; i++) {
Utilizar um nome de variavel mais descritivo no lugar de i, por exemplo index

2021-11-01 13:48 UTC, alanrocha-helpper commented on src/task-2/item-b/index.ts
> +  for (let i = 0; i < persons.length; i++) {
Utilizar um nome de variavel mais descritivo no lugar de i, por exemplo index

2021-11-01 13:48 UTC, alanrocha-helpper commented on src/task-2/item-d/index.ts
> +function updateItemFromIdFunctional(id: number): IMyObject[] {
Receber como parâmetro, também o que vai ser alterado ( nome ou bio ), e o novo valor, e depois realizar a alteração

2021-11-01 13:48 UTC, alanrocha-helpper commented on src/task-2/item-c/index.ts
> +  for (let i = 0; i < persons.length; i++) {
Utilizar um nome de variavel mais descritivo no lugar de i, por exemplo index

2021-11-01 13:48 UTC, alanrocha-helpper commented on src/task-2/item-d/index.ts
> +  for (let i = 0; i < persons.length; i++) {
Utilizar um nome de variavel mais descritivo no lugar de i, por exemplo index

2021-11-01 14:59 UTC, felipedias-dev commented on src/task-2/item-d/index.ts
> +function updateItemFromIdFunctional(id: number): IMyObject[] {
Perfeito... Eu tinha feito dessa forma na primeira vez, mas a descrição da atividade me deixou em dúvida, então desfiz o recebimento via parâmetro. Vou corrigir.

2021-11-01 16:47 UTC, felipedias-dev commented on src/task-2/item-a/index.ts
> +  for (let i = 0; i < persons.length; i++) {
Corrigido.

2021-11-01 16:47 UTC, felipedias-dev commented on src/task-2/item-b/index.ts
> +  for (let i = 0; i < persons.length; i++) {
Corrigido.

2021-11-01 16:47 UTC, felipedias-dev commented on src/task-2/item-c/index.ts
> +  for (let i = 0; i < persons.length; i++) {
Corrigido.

2021-11-01 16:48 UTC, felipedias-dev commented on src/task-2/item-d/index.ts
> +  for (let i = 0; i < persons.length; i++) {
Corrigido.

2021-11-04 21:30 UTC, alanrocha-helpper approved these changes

2021-11-07 20:45 UTC, closed without merging