add task 4
felipedias-dev/helpper-origins-sprint-01 pull request #4
Opened 2021-10-31 06:36 UTC by felipedias-dev

2021-11-04 23:21 UTC, alanrocha-helpper requested changes

2021-11-04 23:21 UTC, alanrocha-helpper commented on src/task-4/index.ts
> +function renderTable(persons: IPerson[] = people): void {
Quebrar essa função, em funções menores, como por exemplo, generateHeader, generateTableBody.

Dica: sempre que função fica muito extensa, é bom deixar comentários para documentar

2021-11-04 23:21 UTC, alanrocha-helpper commented on src/task-4/index.ts
> +function deletePersonFromId(id: number): void {
Funciona, Dica de melhoria: utilizando a função filter() você resolveria com uma função só e facilitaria o entendimento

2021-11-04 23:21 UTC, alanrocha-helpper commented on src/task-4/index.ts
> +function updatePerson(personData: IUpdatePersonDTO): void {
Esse é um comentário de possivel melhoria, não foi reprovado por ele, Mas você poderia ter resolvido tudo usando a função map()

2021-11-04 23:21 UTC, alanrocha-helpper commented on src/task-4/index.ts
> +function showEditionForm(person: IPerson): void {
Quebrar essa função em funções menores.

2021-11-07 19:45 UTC, felipedias-dev commented on src/task-4/index.ts
> +function renderTable(persons: IPerson[] = people): void {
Corrigido.

2021-11-07 20:01 UTC, felipedias-dev commented on src/task-4/index.ts
> +function deletePersonFromId(id: number): void {
Não entendi como utilizar o filter no lugar do splice nesse caso, já que a minha intenção é realmente remover o item do array, assim como removeria um registro do banco de dados, e não apenas retornar um novo array para ser renderizado.

2021-11-07 20:38 UTC, felipedias-dev commented on src/task-4/index.ts
> +function updatePerson(personData: IUpdatePersonDTO): void {
Corrigido.

2021-11-07 20:38 UTC, felipedias-dev commented on src/task-4/index.ts
> +function showEditionForm(person: IPerson): void {
Corrigido.

2021-11-08 20:44 UTC, alanrocha-helpper approved these changes

2021-11-08 20:44 UTC, merged